easy_admin:
  site_name: '<img src="/admin/images/logo.png_png">'
  list:
    max_results: 10
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@VichUploader/Form/fields.html.twig'
      - '@AdminLTE/layout/default-layout.html.twig'
    assets:
      favicon: '/config/images/logo.png'
      css:
        - '/admin/css/custom.css'
      js:


  entities:

    User:
      class: App\Entity\User
      controller: App\Controller\UserAdminController
      form: {fields: [username, email, role, password,isActive]}
