<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\Api\\DatabaseController::newGallery' => ['privates', '.service_locator.HlfXhri', 'get_ServiceLocator_HlfXhriService.php', true],
    'App\\Controller\\Api\\DatabaseController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Api\\EmotionsApiController::emotions' => ['privates', '.service_locator.HlfXhri', 'get_ServiceLocator_HlfXhriService.php', true],
    'App\\Controller\\Api\\EmotionsApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Api\\EventsApiController::consoleRequest' => ['privates', '.service_locator.rakKIaw', 'get_ServiceLocator_RakKIawService.php', true],
    'App\\Controller\\Api\\EventsApiController::dataRequest' => ['privates', '.service_locator.HlfXhri', 'get_ServiceLocator_HlfXhriService.php', true],
    'App\\Controller\\Api\\EventsApiController::eventRequest' => ['privates', '.service_locator.HlfXhri', 'get_ServiceLocator_HlfXhriService.php', true],
    'App\\Controller\\Api\\EventsApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Api\\GalleryApiController::galleryRequest' => ['privates', '.service_locator.bvxq.39', 'get_ServiceLocator_Bvxq_39Service.php', true],
    'App\\Controller\\Api\\GalleryApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\AuthenticationController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\Api\\DatabaseController:newGallery' => ['privates', '.service_locator.HlfXhri', 'get_ServiceLocator_HlfXhriService.php', true],
    'App\\Controller\\Api\\DatabaseController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Api\\EmotionsApiController:emotions' => ['privates', '.service_locator.HlfXhri', 'get_ServiceLocator_HlfXhriService.php', true],
    'App\\Controller\\Api\\EmotionsApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Api\\EventsApiController:consoleRequest' => ['privates', '.service_locator.rakKIaw', 'get_ServiceLocator_RakKIawService.php', true],
    'App\\Controller\\Api\\EventsApiController:dataRequest' => ['privates', '.service_locator.HlfXhri', 'get_ServiceLocator_HlfXhriService.php', true],
    'App\\Controller\\Api\\EventsApiController:eventRequest' => ['privates', '.service_locator.HlfXhri', 'get_ServiceLocator_HlfXhriService.php', true],
    'App\\Controller\\Api\\EventsApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\Api\\GalleryApiController:galleryRequest' => ['privates', '.service_locator.bvxq.39', 'get_ServiceLocator_Bvxq_39Service.php', true],
    'App\\Controller\\Api\\GalleryApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\AuthenticationController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
