<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.messenger_consume_messages' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php';

$this->privates['console.command.messenger_consume_messages'] = $instance = new \Symfony\Component\Messenger\Command\ConsumeMessagesCommand(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'messenger.bus.default' => ['services', 'message_bus', 'getMessageBusService', false],
]), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, []), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()), [], [0 => 'messenger.bus.default']);

$instance->setName('messenger:consume-messages');

return $instance;
