<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.handler_stack.netsuite' shared service.

include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/HandlerStack.php';

$this->services['eight_points_guzzle.handler_stack.netsuite'] = $instance = \GuzzleHttp\HandlerStack::create();

$instance->push(($this->services['eight_points_guzzle.middleware.log.netsuite'] ?? $this->load('getEightPointsGuzzle_Middleware_Log_NetsuiteService.php'))->log(), 'log');
$instance->after('log', ($this->services['eight_points_guzzle.middleware.request_time.netsuite'] ?? $this->load('getEightPointsGuzzle_Middleware_RequestTime_NetsuiteService.php')), 'request_time');
$instance->push(($this->services['eight_points_guzzle.middleware.symfony_log'] ?? $this->load('getEightPointsGuzzle_Middleware_SymfonyLogService.php')), 'symfony_log');
$instance->push(($this->services['eight_points_guzzle.middleware.profile.netsuite'] ?? $this->load('getEightPointsGuzzle_Middleware_Profile_NetsuiteService.php'))->profile(), 'profile');
$instance->unshift(($this->services['eight_points_guzzle.middleware.event_dispatch.netsuite'] ?? $this->load('getEightPointsGuzzle_Middleware_EventDispatch_NetsuiteService.php'))->dispatchEvent(), 'events');

return $instance;
