<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Helper\ExceptionCode' shared autowired service.

include_once $this->targetDirs[3].'/src/Helper/ExceptionCode.php';

return $this->privates['App\Helper\ExceptionCode'] = new \App\Helper\ExceptionCode();
