<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'eight_points_guzzle.client.netsuite' shared service.

include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/HandlerStack.php';

$a = \GuzzleHttp\HandlerStack::create();
$a->push(($this->services['eight_points_guzzle.middleware.log.netsuite'] ?? $this->load('getEightPointsGuzzle_Middleware_Log_NetsuiteService.php'))->log(), 'log');
$a->after('log', ($this->services['eight_points_guzzle.middleware.request_time.netsuite'] ?? $this->load('getEightPointsGuzzle_Middleware_RequestTime_NetsuiteService.php')), 'request_time');
$a->push(($this->services['eight_points_guzzle.middleware.symfony_log'] ?? $this->load('getEightPointsGuzzle_Middleware_SymfonyLogService.php')), 'symfony_log');
$a->push(($this->services['eight_points_guzzle.middleware.profile.netsuite'] ?? $this->load('getEightPointsGuzzle_Middleware_Profile_NetsuiteService.php'))->profile(), 'profile');
$a->unshift(($this->services['eight_points_guzzle.middleware.event_dispatch.netsuite'] ?? $this->load('getEightPointsGuzzle_Middleware_EventDispatch_NetsuiteService.php'))->dispatchEvent(), 'events');

return $this->services['eight_points_guzzle.client.netsuite'] = new \App\Client\NetSuiteClient(['base_uri' => 'http://mobily.ws', 'handler' => $a, 'timeout' => 30.0, 'http_errors' => true, 'headers' => ['User-Agent' => 'EightPointsGuzzleBundle/v7']]);
