<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'messenger.middleware.send_message' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Middleware/SendMessageMiddleware.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Sender/SendersLocatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Transport/Sender/SendersLocator.php';

return $this->privates['messenger.middleware.send_message'] = new \Symfony\Component\Messenger\Middleware\SendMessageMiddleware(new \Symfony\Component\Messenger\Transport\Sender\SendersLocator([], []));
