<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'templating' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/templating/EngineInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/templating/StreamingEngineInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/templating/DelegatingEngine.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/EngineInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Templating/DelegatingEngine.php';

$this->services['templating'] = $instance = new \Symfony\Bundle\FrameworkBundle\Templating\DelegatingEngine($this, []);

$instance->addEngine(($this->privates['templating.engine.twig'] ?? $this->load('getTemplating_Engine_TwigService.php')));
$instance->addEngine(($this->privates['templating.engine.php'] ?? $this->load('getTemplating_Engine_PhpService.php')));

return $instance;
