<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Validator\ViewDataValidator' shared autowired service.

include_once $this->targetDirs[3].'/src/Validator/ValidationData.php';
include_once $this->targetDirs[3].'/src/Validator/ViewDataValidator.php';

return $this->privates['App\Validator\ViewDataValidator'] = new \App\Validator\ViewDataValidator();
